# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-03 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import molo.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('profiles', '0004_add_profile_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityQuestion',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Security Question',
            },
            bases=(molo.core.models.TranslatablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='SecurityQuestionIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='userprofilessettings',
            name='num_security_questions',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Number of security questions asked for password recovery'),
        ),
        migrations.AddField(
            model_name='userprofilessettings',
            name='password_recovery_retries',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Max number of password recovery retries before lockout'),
        ),
        migrations.AddField(
            model_name='userprofilessettings',
            name='security_questions_required',
            field=models.BooleanField(default=False, verbose_name='Security questions required'),
        ),
        migrations.AddField(
            model_name='userprofilessettings',
            name='show_security_question_fields',
            field=models.BooleanField(default=False, verbose_name='Add security question fields to registration'),
        ),
        migrations.AddField(
            model_name='securityanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.SecurityQuestion'),
        ),
        migrations.AddField(
            model_name='securityanswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.UserProfile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='security_question_answers',
            field=models.ManyToManyField(through='profiles.SecurityAnswer', to='profiles.SecurityQuestion'),
        ),
    ]
