# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-30 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('profiles', '0008_change_num_security_questions_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityquestion',
            name='id',
        ),
        migrations.AddField(
            model_name='securityquestion',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='securityquestion',
            name='question',
            field=models.CharField(help_text=b'The question to be asked.', max_length=250),
        ),
    ]
