# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-30 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_change_num_security_questions_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityquestion',
            name='question_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='securityquestion',
            name='question_nr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='securityquestion',
            name='question_ss',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='securityquestion',
            name='question_st',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='securityquestion',
            name='question_tn',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='securityquestion',
            name='question_ts',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='securityquestion',
            name='question_ve',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='securityquestion',
            name='question_xh',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='securityquestion',
            name='question_zu',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
