# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-21 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_create_security_question_index_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilessettings',
            name='country_code',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='The country code that should be added to a user from this sitee.g +27'),
        ),
    ]
