# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-19 14:52
from __future__ import unicode_literals

from django.db import migrations


def remove_existing_security_questions(apps, schema_editor):
    SecurityQuestion = apps.get_model('profiles', 'SecurityQuestion')
    SecurityAnswer = apps.get_model('profiles', 'SecurityAnswer')

    # Delete existing security questions and security answers:
    SecurityAnswer.objects.all().delete()
    SecurityQuestion.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_create_security_question_index_page'),
    ]

    operations = [
        migrations.RunPython(remove_existing_security_questions),
    ]
