# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-20 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_add_curent_site_to_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='education_level',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='userprofilessettings',
            name='activate',
            field=models.BooleanField(default=False, verbose_name='Activate'),
        ),
        migrations.AddField(
            model_name='userprofilessettings',
            name='capture',
            field=models.BooleanField(default=False, verbose_name='Capture on registration'),
        ),
        migrations.AddField(
            model_name='userprofilessettings',
            name='required_field',
            field=models.BooleanField(default=False, verbose_name='Required field'),
        ),
    ]
